/*
 * Copyright (c) 2014, Boston University
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or 
 * without modification, are permitted provided that the following 
 * conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 *    
 * 2. Redistributions in binary form must reproduce the above copyright 
 *    notice, this list of conditions and the following disclaimer in 
 *    the documentation and/or other materials provided with the distribution.
 *    
 * 3. Neither the name of the copyright holder nor the names of its 
 *    contributors may be used to endorse or promote products derived 
 *    from this software without specific prior written permission.
 *    
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.cidarlab.minieugene.predicates.templating;

import java.util.List;
import java.util.UUID;

import org.cidarlab.minieugene.dom.Component;
import org.cidarlab.minieugene.predicates.Constraint;

public abstract class TemplatingPredicate 
	extends Constraint {
	
	private String name;
	private List<List<Component>> components;
	private boolean negated;
	
	protected boolean bAutoGenerated;
	
	/**
	 * 
	 * @param name
	 * @param components
	 * @param isNegated
	 */
	TemplatingPredicate(String name, List<List<Component>> components, boolean isNegated) {

		if(null != name && !name.isEmpty()) {
			this.name = name;
			bAutoGenerated = false;
		} else {
			this.name = UUID.randomUUID().toString();
			bAutoGenerated = true;
		}
		
		this.components = components;
		this.negated = isNegated;
	}

	/**
	 * 
	 */
	public void setNegated() {
		this.negated = true;
	}
	
	/**
	 * 
	 * @return
	 */
	public boolean isNegated() {
		return this.negated;
	}
	
	/**
	 * 
	 * @return
	 */
	public List<List<Component>> getComponents() {
		return this.components;
	}
	
	/**
	 * 
	 * @return
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * 
	 */
	
}
