package org.cidarlab.minieugene.constants;

public enum RuleOperator {
	/* UNARY STRUCTURAL/POSITIONAL RULES */
	STARTSWITH, ENDSWITH,
	
	/* BINARY STRUCTURAL/POSITIONAL RULES */
	AFTER, ALL_AFTER, SOME_AFTER, 
	NEXTTO, ALL_NEXTTO, SOME_NEXTTO,
	LEFTTO, ALL_LEFTTO, SOME_LEFTTO,
	RIGHTTO, ALL_RIGHTTO, SOME_RIGHTTO,
	ALL_BEFORE, BEFORE,  SOME_BEFORE,
	
	/* NUMBERING/COUNTING RULES */
	CONTAINS, NOTCONTAINS, 
	MORETHAN, NOTMORETHAN, 
	EXACTLY, NOTEXACTLY,
	SAME_COUNT,

	/*
	 * ORIENTATION
	 */
	REVERSE, SOME_REVERSE, ALL_REVERSE,
	FORWARD, SOME_FORWARD, ALL_FORWARD,
	SAME_ORIENTATION, ALL_SAME_ORIENTATION, SOME_SAME_ORIENTATION, 
	ALTERNATE_ORIENTATION,
	
	/* RELATIONSHIP RULES */
	REPRESSES, INDUCES, DRIVES, BINDS, MATCHES,	
	
	/* PAIRING RULES */
	NOTTHEN, THEN, WITH, NOTWITH, NOTEQUALS, EQUALS,
	ALWAYS_NEXTTO
}
